name: Record scheduled live
on:
  schedule:
    # Среда 18:00 Киев → 14:55 UTC
    - cron: '55 14 * * 3'
    # Суббота 09:00 Киев → 05:55 UTC
    - cron: '55 5 * * 6'
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - run: |
          sudo apt-get update -y && sudo apt-get install -y ffmpeg rclone
          pip install yt-dlp
      - run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
      - run: python yt-recorder.py
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
