name: YouTube Live Recorder

# run every 5 minutes around the clock
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    # kill any earlier job if a new run starts
    concurrency:
      group: live-recorder
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg rclone
          pip install yt-dlp

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Run recorder
        env:
          CHANNEL_ID: "UCFn8ooPuQL2QaKTAl0jjIcQ"
        run: python yt-recorder.py
